-- Phase 1 schema patch
CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  platform VARCHAR(100) NOT NULL,
  username VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  browser_profile_id BIGINT NULL,
  credential_json LONGTEXT NULL,
  metadata_json LONGTEXT NULL,
  created_at DATETIME NOT NULL
);

ALTER TABLE tasks ADD COLUMN account_id BIGINT NULL;
ALTER TABLE tasks ADD COLUMN is_enabled TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE tasks ADD COLUMN schedule_type VARCHAR(50) NOT NULL DEFAULT 'manual';
ALTER TABLE tasks ADD COLUMN schedule_config_json LONGTEXT NULL;
ALTER TABLE tasks ADD COLUMN next_run_at DATETIME NULL;
ALTER TABLE tasks ADD COLUMN last_run_at DATETIME NULL;
